version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  reviewers:
  - ewanharris
  ignore:
  - dependency-name: got
    versions:
    - "> 9.6.0"
  - dependency-name: "@types/node"
    versions:
    - "> 12.12.0"
  - dependency-name: "@types/vscode"
    versions:
    - "> 1.49.0"
