name: CI
on:
  - pull_request
  - push

jobs:
  Test:
    name: ${{ matrix.os }} - Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install NPM dependencies
        run: npm ci
      - name: Run Tests
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm run test

  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install NPM dependencies
        run: npm ci
      - name: Type Check
        run: npm run compile
      - name: Lint
        run: npm run lint
